In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print("Environment is ready!")
print("Pandas version:", pd.__version__)

Environment is ready!
Pandas version: 3.0.3

In [9]:
# Load the 4 core MovieLens files
ratings = pd.read_csv('../data/raw/rating.csv')
movies = pd.read_csv('../data/raw/movie.csv')
tags = pd.read_csv('../data/raw/tag.csv')
links = pd.read_csv('../data/raw/link.csv')

print("All files loaded successfully!")

All files loaded successfully!

In [3]:
import os
print("Current working directory:", os.getcwd())

Current working directory: c:\Users\Ridmi\Documents\movie-recommender\notebooks

In [7]:
import os
print(os.listdir('../data/raw'))

['genome_scores.csv', 'genome_tags.csv', 'link.csv', 'movie.csv', 'rating.csv', 'tag.csv']

In [8]:
import os
print("Contents of project root:")
print(os.listdir('..'))

Contents of project root:
['data', 'notebooks', 'venv']

In [10]:
# Basic stats for the ratings dataset
print("RATINGS DATASET")
print("Shape (rows, columns):", ratings.shape)
print("\nData types:")
print(ratings.dtypes)
print("\nMissing values:")
print(ratings.isnull().sum())
print("\nFirst 5 rows:")
ratings.head()

RATINGS DATASET
Shape (rows, columns): (20000263, 4)

Data types:
userId         int64
movieId        int64
rating       float64
timestamp        str
dtype: object

Missing values:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

First 5 rows:

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [11]:
# Basic stats for the movies dataset
print("MOVIES DATASET")
print("Shape:", movies.shape)
print("\nMissing values:")
print(movies.isnull().sum())
print("\nFirst 5 rows:")
movies.head()

MOVIES DATASET
Shape: (27278, 3)

Missing values:
movieId    0
title      0
genres     0
dtype: int64

First 5 rows:

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [12]:
# Basic stats for the tags dataset
print("TAGS DATASET")
print("Shape:", tags.shape)
print("\nMissing values:")
print(tags.isnull().sum())
print("\nFirst 5 rows:")
tags.head()

TAGS DATASET
Shape: (465564, 4)

Missing values:
userId        0
movieId       0
tag          16
timestamp     0
dtype: int64

First 5 rows:

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [13]:
# Basic stats for the links dataset
print("LINKS DATASET")
print("Shape:", links.shape)
print("\nMissing values:")
print(links.isnull().sum())
print("\nFirst 5 rows:")
links.head()

LINKS DATASET
Shape: (27278, 3)

Missing values:
movieId      0
imdbId       0
tmdbId     252
dtype: int64

First 5 rows:

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0